### ISSUE TITLE
Ignore node_modules [help wanted]

### ISSUE THREAD

**Issue by EvilPuppet** [eugen0329/vim-esearch#101]
How i can ignore node_modules ? thx

**Comment by eugen0329** [comment]
Hi,

As any plugin, ESearch delegates search to a separate binaries to work faster, so the answer depends on what you are using.
If it's [ag](https://github.com/ggreer/the_silver_searcher), the solution is to add a line into .agignore file using `echo node_modules >> ~/.agignore` command in you shell. For rg it's [.ignore](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#automatic-filtering) , pt supporots [.ptignore](https://github.com/monochromegane/the_platinum_searcher/pull/26)

Some adapters allow to set exclude rules per command, so, for example, for grep you can add `let g:esearch#adapter#grep#options = '--exclude-dir=node_modules` to your vimrc (instead `#grep#` you can use any other available adapter name).

**Comment by EvilPuppet** [comment]
thx worked
