### ISSUE TITLE
Preview feature

### ISSUE THREAD

**Issue by eugen0329** [eugen0329/vim-esearch#106]

**Comment by eugen0329** [comment]
@ipod825 I can expose the following events to customize opening:
```
esearch#out#win#open_pre
esearch#out#win#opened
esearch#out#win#open_jump_back " or a better name
```
The first will run before doing anything within a search win.
The second is fired when within an opened window. 
The last is executed after returning back and won't be executed if `'stay'` is not provided.

Another suggestion is to add another option `'let!'`  to set vars and options within a buffer in addition to already existing `'let'` that sets variables temporary (may be used to set flags for some plugins or disable some options like updatecount etc.). Exclamation signifies that it does mutation, which is fine as some languages including viml also use this, but the problem is that it may be confusing for new users.
Although, it'd help to make vimrc files more skinny for experienced ones by having only one-liner configs, as opposed to implementation with longer names.

**Comment by eugen0329** [comment]
> So altering them in a preview window actually alter users' setting to the buffer

I suppose, it can be done by setting `foldlevel` which is local to window.

> This seems to be an ugly solution

"Welcome to the world of vim, please, follow me". One of the biggest flaws of vim is that not all options have buffer/window/tab/global scopes like variables do, so we have not that many ways to handle things to not corrupt user's configurations. Folds is a general case and luckily it can be fixed using setting window-local option `foldlevel`. But I think it should be done by default only for floating previews. API should remain generic and to not imply dozens of unexpected actions inside.

**Comment by ipod825** [comment]
> The last is executed after returning back and won't be executed if 'stay' is not provided.
Yeah, that should work. It's just disappointing that user should deal with this stuff.

> I suppose it can be done by setting foldlevel which is local to window.
No. I've tested it. It's again local to buffer instead of window. I've encountered this problem when writing the preview functionality in my plugin at this [line](https://github.com/ipod825/vim-netranger/blob/52f730027f3d862247d906019b8919e4c0707cdf/pythonx/netranger/netranger.py#L883).

**Comment by eugen0329** [comment]
> Yeah, that should work. It's just disappointing that user should deal with this stuff.

There are options for both preview kinds in #107. Please, take a look. But in short - floating preview will work nice. For split previews there is a more graceful implementation to do this instead of autocmd hooks.

> No. I've tested it. It's again local to buffer instead of window

The same conclusion is in the PR. Previously opened windows aren't affected, while all the windows opened further will inherit this option like if it's buffer local. We can try to overcome it by setting up autocommands to restore the values, but there are too many efforts to achieve this, so I'd just accept it as is.
