### ISSUE TITLE
Can't correctly install the plugin on windows with VimPlug

### ISSUE THREAD

**Issue by AbdelghaniDr** [eugen0329/vim-esearch#11]
VimPlug complains about the fact it can't `git checkout` files because of this folder [+some str%nge|name}](https://github.com/eugen0329/vim-esearch/tree/master/spec/fixtures/plugin/%2Bsome%20str%25nge%7Cname%7D) which can't be saved on windows. so it can't complete the install and eventual updates cleanly.
is there a workaround for that ?

**Comment by eugen0329** [comment]
Fixed in e87e722. Please, feel free to reopen the issue if the error still occurs.

**Comment by AbdelghaniDr** [comment]
Thank you for the quick reply, the plugin installs now correctly
