### ISSUE TITLE
How to add ignored directories?

### ISSUE THREAD

**Issue by iiison** [eugen0329/vim-esearch#120]
Hello guys, thanks for the awesome plugin. I have a quick question about searching for a pattern: Due to a lot of system generated files in one directory, my results are mostly very cluttered, as it shows most of the results from this directory. I was wondering if there is a way to add a list of the ignored directories in configs or something?

Thanks :)

**Comment by eugen0329** [comment]
Hi, thanks for the report.

The preferred way is to put unwanted names into `~/.ignore` file or use adapter-specific ones like `~/.agignore`, `~/.rgignore` etc.
Alternatively, you can temporary switch to `development` branch. It has lots of features to work with paths including setting paths per request, searching only in modified files and others. Examples can be found in `:help esearch-api-examples`.
