### ISSUE TITLE
Highlight results in preview window?

### ISSUE THREAD

**Issue by fritzblue** [eugen0329/vim-esearch#129]
First, thank you so much for your work on this plugin. It's by far the best plugin I've found for project-wide search in Vim.

One small feature that would make it even better would be to highlight the results in the preview window. I use the auto-preview as described in the readme, and it is sometimes hard to quickly parse where in the preview the match has occurred.

Thoughts?

**Comment by fritzblue** [comment]
Beyond just highlighting, it would be even nicer if the window was already in `/` search mode when entered

**Comment by eugen0329** [comment]
Thanks for your report.

Readme contains split preview example which is mentioned for compatibility sake. If you use neovim of version 0.4 or later, you can build autopreview on top of floating preview feature.
```vim
    autocmd User esearch_win_config
      \  let b:autopreview = esearch#async#debounce(b:esearch.preview_open, 100)
      \| autocmd CursorMoved <buffer> call b:autopreview.apply({
      \    'emphasis': [esearch#emphasis#sign(), esearch#emphasis#highlighted_line()],
      \    'close_on': [],
      \    'align': 'right'})
```
Emphasis feature isn't available for split_preview and it's not documented for floating previews yet as I'm not sure about the api.
I can additionally implement another emphasis kind to highlight only matching text, but it's easier for me to notice the entire line highlight.

**Comment by eugen0329** [comment]
> Beyond just highlighting, it would be even nicer if the window was already in / search mode when entered

If you prefer to use `/` search instead of the default you can try `let g:esearch.win_matches_highlight_strategy = 'hlsearch'`.
But if you want to start `/` search only when a file is opened from the search window, you can try the following api call:
```vim
call b:esearch.open('edit', {'let!': {'@/': b:esearch.pattern.vim}})
```

**Comment by eugen0329** [comment]
UPD Search register `@/` can be easily set, but it requires a small hack that all plugins do to start the highlight from source.
```vim
nnoremap <plug>edit&set@/ :call b:esearch.open('edit', {'let!': {'@/': b:esearch.pattern.vim}})<cr>

let g:esearch.win_map = [['n', '<enter>', '<plug>edit&set@/<plug>(-esearch-enable-hlsearch)']]
```

**Comment by fritzblue** [comment]
Very helpful info, thank you for the feedback!

**Comment by eugen0329** [comment]
Vim8 preview is also implemented, so the API is more brief now:
```vim
autocmd User esearch_win_config
  \  let b:autopreview = esearch#async#debounce(b:esearch.preview_open, 100)
  \| autocmd CursorMoved <buffer> call b:autopreview.apply({'align': 'right'})
```

Also note, that there are many new features like output updates on the fly while you're typing, git commits grepping and browsing, configurable write behavior (background by default), AST grepping with semgrep or gogrep and others. Please, update if you're interested.
