### ISSUE TITLE
How would you scope your search to files matching by pattern?

### ISSUE THREAD

**Issue by NullVoxPopuli** [eugen0329/vim-esearch#149]
I've been looking for something as easy as VS Code's search (so far, I only use VS Code for two things: project-wide searching, and git conflict resolution).

I'd like
 - search / find & replace (also with patterns)
 - include / exclude file patterns (like: `folder-a/**/package.json`)

is that possible with this plugin?

**Comment by eugen0329** [comment]
Short answer: yes.

1. To open the search input use `<leader>ff` and insert your pattern. Press `<c-r><c-r>` within the input to enable regex mode. Configure `let g:esearch = {'regex': 1}` to search for regex by default.
Edit search results as usual (including with `:s/`) and save your edits into files using `:write` command. Alternatively, use `let g:esearch = {'out': 'qflist'}` to output results into QuickFix list if you prefer it more.

2. Include / exclude file patterns are done via shell globs. To configure them dynamically open the menu using `<c-o>` and press `p` to open paths input. To configure paths globally use `let g:esearch = {'paths': 'folder-a/**/package.json'}`. To add a separate keymap use 
`nnoremap <leader>fp :call esearch#init({'paths': 'folder-a/**/package.json/'})<cr>`

**Comment by eugen0329** [comment]
If I got your correct, there are always two ways to do things with this plugin: on the fly by opening paths input field from the menu and via adding a config (mentioned only for demonstration).

If you mean you need to have multiple fields for search patterns, you can press `<c-p>` to start another pattern inputting, but it's only supported by rg, git and some other adapters.

**Comment by eugen0329** [comment]
I'm closing it. Please, feel free to ask other questions if you have any.
