### ISSUE TITLE
Error detected while processing function esearch#init

### ISSUE THREAD

**Issue by ricbermo** [eugen0329/vim-esearch#154]
Hello there, after updating the version this morning I started getting this error. It is happening with both the defaults and using the same config I can find in the README.

![image](https://user-images.githubusercontent.com/2601363/98138922-9b540c80-1e91-11eb-84ef-c71dfad5bc6b.png)

Let me know how I could help fixing this issue

**Comment by eugen0329** [comment]
Hi. Could you provide your colorscheme name, please?

**Comment by ricbermo** [comment]
lol, sure https://github.com/chuling/equinusocio-material.vim

**Comment by eugen0329** [comment]
It seems to be gui only, so it failed on guessing the best color for `+` virtual sign. Please, pull the latest commit and try again.

**Comment by ricbermo** [comment]
it's working fine!! Thanks
