### ISSUE TITLE
Is there a way to pass flags for rg?

### ISSUE THREAD

**Issue by ahmedelgabri** [eugen0329/vim-esearch#158]
For example, I want to limit to a specific filetype in the CLI I'd do `rg -tvim colorscheme` then `rg` will only search all `.vim` files. How can I do this? I tried passing the flags directly but that didn't work.

**Comment by eugen0329** [comment]
For filetypes:
1. Open the menu using `<c-o>` within the input prompt.
2. Press `f` or locate the entry using `j`/`k` and `<cr>` to open the input and insert space separated filetypes. Use `<tab>` completion for hints.

Use `let g:esearch.filetypes = 'vim cpp h'` to set filetypes permanently or define a separate keymap `nnoremap <leader>fv :call esearch#init({'filetypes': 'vim cpp h'})<cr>`.

For arbitrary raw options: `let g:esearch.adapters = {'rg': {'options': '--search-zip --sort path'}}`. However, this api isn't documented as it is not stable and can be changed in the future.

**Comment by ahmedelgabri** [comment]
Thanks @eugen0329
