### ISSUE TITLE
Reset search path after search in filebrowser.

### ISSUE THREAD

**Issue by ipod825** [eugen0329/vim-esearch#159]
Currently once you search in a file browser plugin such as vim-netranger. The search path will be persistent in next search in a plain file. Is there a way to avoid this?

**Comment by eugen0329** [comment]
Try this:
```vim
au FileType netranger nnoremap <buffer><leader>ff :call esearch#init({'remember': []})<cr>
au FileType netranger xnoremap <buffer><expr><leader>f  esearch#prefill({'remember': []})
```

See `:help g:esearch.remember` for default configs to remember between search requests. E.g. you can pass `['last_pattern', 'case', 'regex', 'textobj']` to persist the last pattern and matching modes.

**Comment by ipod825** [comment]
Thanks!
