### ISSUE TITLE
esearch removes numbers from iskeyword

### ISSUE THREAD

**Issue by tmccombs** [eugen0329/vim-esearch#18]
This line: https://github.com/eugen0329/vim-esearch/blob/master/autoload/esearch/out/win.vim#L94
sets the iskeyword to a pattern that doesn't include numbers. This breaks word traversal over "words" that contain numbers. I'm not sure if ommiting number is intentional or not, but it seems like that should be a `setlocal iskeyword` rather than a `let &keyword`.

**Comment by eugen0329** [comment]
Seems, it's legacy option that is not required anymore. Removed in 1253488.

If you need to customize options of a search window you can use `esearch` filetype. For example:

```viml
au FileType esearch setlocal iskeyword=a-z,A-Z,_,0-9,#
```

**Comment by tmccombs** [comment]
Thanks! :+1:
