### ISSUE TITLE
Results on Popup

### ISSUE THREAD

**Issue by ozkanonur** [eugen0329/vim-esearch#187]
The popup configuration in docs looks like works only on Neovim. Is there configuration also for vanilla Vim(+8)?

**Comment by eugen0329** [comment]
If you're asking about file content previews, then yes, you'll have your previews in a popup using vanilla vim8.

If the questions is about running the entire search window in the popup, then unfortunately no. It's not feasible right now as unlike neovim floating windows, vim8 popups aren't focusable. The only exception is when a terminal app is executed like it's done in floatterm plugin, but esearch is a viml plugin, not a terminal app.

**Comment by ozkanonur** [comment]
What do you mean with vim8 popups are not focusable?

For example, using `junegunn/fzf.vim` plugin I can do single file searching in a popup window as in the screenshot below. What is the difference that we can not provide this functionality in vim-esearch?

![2021-08-10_12-59](https://user-images.githubusercontent.com/39852038/128847916-f56e870b-d9bf-43cb-a1e6-8260a8e1023b.png)

**Comment by eugen0329** [comment]
From `:h popup-intro`:
```
The popup window contains a buffer, and that buffer is always associated with
the popup window. The window cannot be in Normal, Visual or Insert mode, it
does not get keyboard focus.
```

FZF runs an external program `fzf` written in go. As far as it's executed in a terminal, the window can be focused, but it doesn't act like a regular buffer.
From `:h popup-terminal`:
```
A special case is running a terminal in a popup window.  Many rules are then
different:                                              E863
- The popup window always has focus.
```
It's a known limitation that is sometimes handled by other plugins using keystrokes interception and setting the popup cursor position remotely without focusing it, but as far the main feature of esearch buffer is an ability to edit it and write changes into files, it's not really possible to do this without Insert mode.

**Comment by ozkanonur** [comment]
Ah, alright. I get you know. Thanks for the detailed explanation.
