### ISSUE TITLE
Save cursor position in long list of search results

### ISSUE THREAD

**Issue by jamesgecko** [eugen0329/vim-esearch#19]
In the default configuration, when I hit enter in the search results to jump to a new buffer, the search buffer disappears. When I press `<leader>ff<cr>` to jump back to the search results, my cursor is always at the top of the search results. This is inconvenient if the results were lengthy. Is there a way to preserve the cursor position in the search result buffer if the query hasn't changed?

**Comment by eugen0329** [comment]
By pressing `<leader>ff<cr>` a second time you actually reload the results. If I understood you right, you may use `<C-o>` (vim builtin mapping) to get to the results list with preserved position.

**Comment by jamesgecko** [comment]
Nice! I hadn't encountered that before, and it fixes a few other vim annoyances I've had, too. Thank you!
