### ISSUE TITLE
t_ve option is missing in neovim (0.8)

### ISSUE THREAD

**Issue by ipod825** [eugen0329/vim-esearch#199]
https://github.com/eugen0329/vim-esearch/blob/d00e5b1f29288e0d884eb523558fea891a252631/autoload/esearch/ui/controllers/menu.vim#L51

As title, now opening option window with `<c-o>` leads to error.
Is there any reason to save this option? From vim's manual, that's an option for the terminal. But I don't think a terminal is involved during the process of opening the menu.

A alternative fix is to just check if the option exists and don't save it if it doesn't exist.

**Comment by 00sapo** [comment]
I have the same problem, please merge the pull request!
