### ISSUE TITLE
ESearch result count varies

### ISSUE THREAD

**Issue by Logout22** [eugen0329/vim-esearch#2]
I am using ESearch with NeoVim 0.1.5. While the_silver_searcher (ag) always finds a constant number of results when I execute it manually, ESearch produces a varying number of results with each run. Could that be a bug in NeoVim's asynchronous routines, or did I just miss some setting? Thanks!

**Comment by eugen0329** [comment]
neovim/neovim#4897

**Comment by Logout22** [comment]
Nice, thank you!

**Comment by eugen0329** [comment]
Note that despite this bug You are free to use another backend.

```vim
let g:esearch = extend(get(g:,'esearch', {}), {'backend':'vimproc'}, 'force')
```
(however, you need to install [vimproc](https://github.com/Shougo/vimproc.vim#install) first)

**Comment by pablasso** [comment]
FYI neovim/neovim#4897 is supposedly fixed in 0.1.5, but I just tried on 0.1.7 and I still get inconsistent results. I had to go back to vimproc.

**Comment by Logout22** [comment]
Have you filed the bug with neovim yet? If so, could you please post a
link here? Thanks!

**Comment by pablasso** [comment]
I haven't sorry. I'm not sure if the problem remains theirs as I only tested with your plugin.

**Comment by eugen0329** [comment]
Issue from neovim side is actually fixed. I can't reproduce results truncation bug with test script based on vimdoc anymore.

But there is another one tied with esearch results parsing. I already  know what is the reason and I think the bug will be fixed in a few days. And thanks for you attention!

**Comment by eugen0329** [comment]
Please, pull the latest version to apply the fix.

**Comment by pablasso** [comment]
I can confirm it works just fine, thanks @eugen0329!
