### ISSUE TITLE
'qflist' value for 'out' option causes an error

### ISSUE THREAD

**Issue by yevhen-m** [eugen0329/vim-esearch#22]
```
pattern (Press ctrl-o ctrl-h to list help) >>> tmuxError detected while processing function esearch#init[60]..esearch#out#qflist#init:
line    5:
E927: Invalid action: ''
```
nvim 2.0, iterm, osx

```
" {{{
let g:esearch = {
            \ 'adapter':    'ag',
            \ 'backend':    'nvim',
            \ 'out':        'qflist',
            \ 'batch_size': 3000,
            \ 'use':        ['visual', 'hlsearch'],
            \}
" }}}
```

**Comment by eugen0329** [comment]
Can you provide the version of neovim? (`:version` command).

P.S. I've made a small change that, I suppose, can fix the problem. Update the plugin and let me know whether it helped.

**Comment by yevhen-m** [comment]
```
NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170503-20396-1cdaxjw/neovim-0.2.0/build/config -I/tmp/neovim-20170503-20396-1cdaxjw/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170503-20396-1cdaxjw/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170503-20396-1cdaxjw/neovim-0.2.0/build/include


Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
```

**Comment by yevhen-m** [comment]
@eugen0329 there is not update. Did you push it?

**Comment by eugen0329** [comment]
Here is e4deb66.

**Comment by yevhen-m** [comment]
@eugen0329 thanks. Now error is fixed. 
But, `ESubstitue` command is not defined now, what is the workflow when `qflist` value for `out` is used?

**Comment by eugen0329** [comment]
I've implemented this feature in `qflist`, but it isn't  tested well yet (since I usually prefer `win`). Please, update esearch and let me know if something goes wrong.
.

**Comment by yevhen-m** [comment]
@eugen0329 Nice, it works )))). Does `ESubstitute` accept all the flags `:s` accepts? It would be more convenient if selected flags during search were applied to substitute as well.

**Comment by eugen0329** [comment]
Vim native `:s` is used behind `ESubstitute` command and flags from `ESubstitute` is directly passed to it. 
I haven't tested the command with each available flag, but `g` and `c` works fine. I suppose,  it will work correctly with the rest flags too.

**Comment by eugen0329** [comment]
Also note, that you don't have to write complete `ESubstitute` command. There are `S` and `ES` synonyms defined  by default (if you or another plugin didn't define it previously).
