### ISSUE TITLE
Provide alternative to vimproc in Vim8

### ISSUE THREAD

**Issue by kirjavascript** [eugen0329/vim-esearch#24]
Thanks for your work on the plugin!

Since Vim8 now has async support, can it be used as a backend - allowing us to drop the vimproc dependency?

**Comment by eugen0329** [comment]
Hey @kirjavascript!

I already have some drafts in a branch [vim8-job-control](https://github.com/eugen0329/vim-esearch/tree/vim8-job-control) (although, I don't remember the readiness status of it). Unfortunately, I won't have much time for the next couple of months, but you are welcome to create a PR.

Here is a good example of how to implement vim8 job control backend with already implemented one for neovim.
https://github.com/prabirshrestha/async.vim

**Comment by kirjavascript** [comment]
Not sure if I'm up to the task personally but thanks for the response/info!

**Comment by eugen0329** [comment]
Anyway, thanks for your attention! I'll try to find a time a bit later to finish the work on it.

**Comment by eugen0329** [comment]
Resolved in #28.
Is not a default for now as it's brand new and potentially unstable (but it works totally fine, no results are missed or currepted), so in order to enable it use:
```vim
let g:esearch = {
  \ 'backend':    'vim8',
  \}
```
