### ISSUE TITLE
Plugin breaks when sourcing configuration file

### ISSUE THREAD

**Issue by jamesgecko** [eugen0329/vim-esearch#25]
After running `:so $MYVIMRC` in Neovim v0.2.0, activating esearch's keyboard shortcut results in the following error message:

```
Error detected while processing function esearch#init[29]..esearch#cmdline#read:
line    9:
E716: Key not present in Dictionary: regex ? a:cmdline_opts.exp.pcre : a:cmdline_opts.exp.literal
E15: Invalid expression: g:esearch.regex ? a:cmdline_opts.exp.pcre : a:cmdline_opts.exp.literal
Press ENTER or type command to continue
```

I'm using the `vim-plug` plugin manager.

**Comment by eugen0329** [comment]
Hey @jamesgecko, thanks for your report!

I've made a couple of changes. Please, try to update the plugin and try again. I hope it helps.

**Comment by eugen0329** [comment]
Feel free to reopen if you face the issue again.
