### ISSUE TITLE
Resulting path when searching in a NERDTree folder are wrong

### ISSUE THREAD

**Issue by MartyLake** [eugen0329/vim-esearch#27]
Steps to reproduce:
- open NERTTree
- select "this" folder ('./')
- search an expression
- expected: in the result window, results path are clickable and go to the corresponding search result file
- observed: in the result window, result path are clickable but go to a new empty file

The path starts with '~' instead of './'

**Comment by eugen0329** [comment]
Can't actually reproduce.

My steps are:
* $ `cd ~/.vim/bundles/vim-esearch`
* $ `vim`
* : `NERDTree`
* move cursor to the first line with current dir (`~/.vim/bundle/vim-esearch/`)
* click `<leader>ff`
* type something and click Enter

Can you type : `map <leader>ff` (or another map that you use) within nerdtree window, please? It should result in something like
```
n  ,ff         *@:call nerdtree#ui_glue#invokeKeyMap("<Leader>ff")<CR>
```

**Comment by MartyLake** [comment]
I don't know what happened, I can't reproduce anymore. Thanks for your support !!!

**Comment by Spope** [comment]
I can reproduce this bug. If I search and open a result globaly it works, but if I search an open a result from NERDTree the path of the file is incorrect.
Ex, I search into the folder service/security/, the path to open a file into the folder will be service/security/service/security/myFile.ext

I'm on Vim 8.1.1 and the output of : `map <leader>ff` into NERDTree is :

    n  <Space>ff   *@:call nerdtree#ui_glue#invokeKeyMap("<leader>ff")<CR>
       <Space>ff     <Plug>(esearch)

**Comment by eugen0329** [comment]
@Spope,
could you provide the output from `:echo [b:esearch, getcwd()]` command inside the window with search result entries and also this window content, please?

I tried with the following hierarchy:
```
/tmp/
   service/
     security/
       myFile.ext
     other_file.txt
```
where `myFile.ext` contains lines that match the required pattern.

For example if I put my cursor there
```
/tmp/
   service/
>>>>>security/<<<<<
       myFile.ext
     other_file.txt
```
and start searching (by pressing `<Space>ff` using your mappings) I'll have `:echo [b:esearch.cwd, getcwd()]` equal to `['/tmp/service/security', '/tmp']` and output window content with the following lines:
```
Matches in 1 lines, 1 file(s). Finished.

myFile.ext
   1 pattern
```

**Comment by Spope** [comment]
Ok, on a new project I do not have the bug. On the existing one I had not setted any configuration for vim-esearch, and it works if I set the adapter to grep. I think it was git by default, here is the output from `:echo [b:esearch, getcwd()]` :

```
[{'syn_regions_loaded': [], 'context_width': {'r': 60, 'l': 60}, 'cwd': '/Users/spope/boulot/betterise-api/src/Kernel/Service', 'errors': [], 'batch_size': 1000, '_columns': {'4': 13, '5': 13, '6': 13, '7': 13, '10': 13}, '_match_highligh
t_id': 44, '__broken_results': [], 'ignore_batches': 1, 'request': {'events': {'update': 'ESearchvim8Update2', 'forced_finish': 'ESearchvim8Finish2'}, 'errors': [], 'aborted': 0, 'status': 0, 'bufnr': 24, 'job_id': 'process 93687 dead', '
jobstart_args': {'cmd': ['/bin/bash', '-c', 'git --no-pager grep --fixed-strings --ignore-case  -H -I --no-color --line-number  -- ''throw new ApiE'' /Users/spope/boulot/betterise-api/src/Kernel/Service'], 'opts': {'in_io': 'null', 'close
_cb': function('<SNR>101_closed', [2]), 'exit_cb': function('<SNR>101_exit', [2]), 'out_cb': function('<SNR>101_stdout', [2]), 'err_cb': function('<SNR>101_stderr', [2])}}, 'command': 'git --no-pager grep --fixed-strings --ignore-case  -H
 -I --no-color --line-number  -- ''throw new ApiE'' /Users/spope/boulot/betterise-api/src/Kernel/Service', 'tick': 5, 'backend': 'vim8', 'internal_job_id': 2, 'finished': 1, 'old_data_ptr': '', 'async': 1, 'ticks': 100, 'out_finish': func
tion('esearch#out#win#_is_render_finished'), 'data': ['src/Kernel/Service/SecurityService.php:112:            throw new ApiException(''204'');', 'src/Kernel/Service/SecurityService.php:120:            throw new ApiException(''204'');', 's
rc/Kernel/Service/SecurityService.php:127:            throw new ApiException(''204'');', 'src/Kernel/Service/SecurityService.php:130:            throw new ApiException(''204'');', 'src/Kernel/Service/Tools.php:458:            throw new Ap
iException(400);'], 'files_count': 2, 'data_ptr': 5}, 'backend': 'vim8', 'exp': {'vim': '\Vthrow new ApiE', 'literal': 'throw new ApiE', 'vim_match': '\c\%>1l\%(\s\+\d\+\s.*\)\@<=\Vthrow new ApiE', 'pcre': ''}, 'title': 'Search `throw new
 ApiE`', 'data': [], 'out': 'win', 'prev_filename': 'src/Kernel/Service/Tools.php', 'without': function('esearch#util#without'), 'adapter': 'git'}, '/Users/spope/boulot/betterise-api']
```
As you can see, the results where found (I search 'throw new ApiEx') :
```
Matches in 5 lines, 2 file(s). Finished.

src/Kernel/Service/SecurityService.php
 112             throw new ApiException('204');
 120             throw new ApiException('204');
 127             throw new ApiException('204');
 130             throw new ApiException('204');

src/Kernel/Service/Tools.php
 458             throw new ApiException(400);
```

It's only when opening one (the first one), the path of the file was incorrect : `"~/boulot/betterise-api/src/Kernel/Service/src/Kernel/Service/SecurityService.php" [New DIRECTORY]`
