### ISSUE TITLE
There is no VIM help for plugin

### ISSUE THREAD

**Issue by petRUShka** [eugen0329/vim-esearch#3]
Having a comprehensive help pages seems to be VIM/NVIM standard for VIM plugins.

It is also very convenient to have all help in one place and not to switch to browser when you need some information about some particular features.

Please, add VIM help pages.

**Comment by eugen0329** [comment]
I will add it within a couple of days.

**Comment by petRUShka** [comment]
Thanks! I'm looking forward for this!

**Comment by petRUShka** [comment]
Just a reminder.

**Comment by eugen0329** [comment]
I remember:) Sorry for procrastinating. I had too intense schedule during the last couple of month.
I have already written [documentation](https://github.com/eugen0329/vim-esearch/blob/master/doc/vim_esearch.txt) for some features. However, there is still plenty of work. Will try to push some updates in the next few days.

**Comment by eugen0329** [comment]
Detailed docs are in master along with editing and many other new features.

Please, take a look (if it's still relevant to you after 4 years :) )
