### ISSUE TITLE
Incorrect path on Windows

### ISSUE THREAD

**Issue by foxbunny** [eugen0329/vim-esearch#35]
With the default configuration, this plugin seems to mangle windows paths. The error is:

```
ERRORS (1)
	ERR: Error opening directory C:Codetest: No such file or directory
```

The intended path was `C:\Code\test`.

**Comment by eugen0329** [comment]
Hi @foxbunny.

Have no chance at the moment to test the plugin in windows. Could you please provide you config here by running `:echo g:esearch` after the first search is done (even with errors) as it's inferred using your installed utils?

**Comment by eugen0329** [comment]
Underlying code is completely rewritten and tested on windows 10. Please, feel free to reopen.

**Comment by google-goldfish** [comment]
Hi @eugen0329 

I'm using this on Windows 11 Powershell, however, rg doesn't return any result when using through your plugin. It does work when I run it through powershell command. What can I do to help you resolve this issue?
