### ISSUE TITLE
Case insensitive search with pt is broken

### ISSUE THREAD

**Issue by pablasso** [eugen0329/vim-esearch#42]
I just upgraded the plugin from a while ago and looks like [this change](https://github.com/eugen0329/vim-esearch/commit/36aeef56058a5a10fb7ab770e73ce74cf3867e92#diff-2c61c4992616db4e3cdde802218d68b0L11) breaks the case-insensitive search. I don't understand what's the TODO about since `-i` only activates case, not regexp. Regexp is used with `-e`.

Is there any special reason why was this changed or can it be reverted?

**Comment by eugen0329** [comment]
Hi, thanks for your report.

I have pt of version 2.1.1. On my machine if I try to use `-i` it implicitly enables regexp matching:
```sh
pt -i '**' # error parsing regexp: missing argument to repetition operator: `*`
```

We could automatically switch to regexp search mode as well when switching to case-insensitive mode (to not confuse users) or as an alternative we could just ignore this catch and just forward all the options to the search util like it's done with others (ag, ack etc.). What do you think?

Also I think it's time to put a note into the README about it.

**Comment by pablasso** [comment]
Ah you're right, when used with `-i` it's trying to match a pattern ([reference](https://github.com/monochromegane/the_platinum_searcher/blob/master/pattern.go#L19)), but it doesn't look that it was meant to work that way ([see the discussion before `-e` was implemented](https://github.com/monochromegane/the_platinum_searcher/pull/27)).

In my opinion you were handling it correctly by letting the user choose between literal and case insensitive — if anything an improvement would be to add a third case for `-e`. I think the user is responsible to know the quirks of the adapter it's choosing,`vim-esearch` can't be expected to handle every special behaviour.

**Comment by eugen0329** [comment]
Alright, I'll try to fix it tomorrow.

**Comment by pablasso** [comment]
I forgot to thank you, it works great now!
