### ISSUE TITLE
esearch not working properly for ripgrep v0.9.0

### ISSUE THREAD

**Issue by ErrEoE** [eugen0329/vim-esearch#43]
On windows 10, use `rg` as search tool, it not show any result.

**Comment by eugen0329** [comment]
Hi ErrEoE. Thanks for reporting!

Could you please provide me more information regarding the issue? E.g. what is you `rg` version, what appears on the screen instead of expected results after searching and what's the out of `:echo g:esearch.slice('adapter', 'backend', 'out', 'batch_size')` command after an unsuccessful search attempt? Thanks.

**Comment by ErrEoE** [comment]
In the search window, it show "Matches in 0 lines, 0 file(s). Finished".

`echo g:esearch.slice('adapter', 'backend', 'out', 'batch_size') | echo b:esearch.request.errors` output:
```
E121: Undefined variable: b:esearch
E15: Invalid expression: b:esearch.request.errors
```

**Comment by eugen0329** [comment]
It's strange that buffer variable wasn't set. Could you try `:echo esearch#backend#vim8#_context().jobs` after searching, please? (it's another way to inspect the request)

**Comment by ErrEoE** [comment]
![1png](https://user-images.githubusercontent.com/14369333/44955660-a7c33000-aee9-11e8-8b00-9b63695b3e48.png)

**Comment by eugen0329** [comment]
According to [exit code value definition](https://www.febooti.com/products/automation-workshop/online-help/events/run-dos-cmd-command/exit-codes/) it may be that your vim cannot execute ag util properly:
```
1 | Incorrect function. Indicates that Action has attempted to execute non-recognized command in Windows command prompt cmd.exe.
```

Could you try to run `:!ag` or any such command to verify that the executable is accessible?

**Comment by ErrEoE** [comment]
I use `:!ag`, it can be executable.

**Comment by eugen0329** [comment]
I have no access to a win10 workstation, but I'll try find a way to test it.

**Comment by ErrEoE** [comment]
I use `system` backend, it can work.

**Comment by eugen0329** [comment]
Output handling is completely rewritten and tested on win10. It should work fine now. Please, reopen if it's still an issue.
