### ISSUE TITLE
Search only certain path in project

### ISSUE THREAD

**Issue by kristijanhusak** [eugen0329/vim-esearch#45]
Hi,

is there a way to search only specific folder in the project? When i do <leader>ff and enter a word for searching, it searches the whole project.

**Comment by eugen0329** [comment]
Hi! If you use nerdtree plugin you can just go there, point your cursor to a directory you need and hit esearch keys combination (by default it's `<leader>ff`). By the way, you can see how it works in the very beginning of the [demo](https://raw.githubusercontent.com/eugen0329/vim-esearch/master/.github/demo.gif) (searching in "autoload" folder).

Another thing you can do is to create own mappings to search in specific directories of your project (that can be nicely combined with [local_vimrc](https://github.com/luchermitte/local_vimrc) or similar):

```vim
map <leader>fs :<C-u>call esearch#init({'cwd': getcwd().'/src'})<CR>
map <leader>ft :<C-u>call esearch#init({'cwd': getcwd().'/test'})<CR>
```

**Comment by kristijanhusak** [comment]
Ok, thanks!
