### ISSUE TITLE
Disable default mappings

### ISSUE THREAD

**Issue by pwntester** [eugen0329/vim-esearch#47]
Hi,

I would like to disable default mapping for `<leader>fw` instead of assigning a new mapping. Im currenly using (as suggested in https://github.com/eugen0329/vim-esearch/issues/8)

```
call esearch#map('//', 'esearch')
" unmapping to not slow down <leader>f
augroup TmpWorkaroundWithEsearch
  au!
  au VimEnter * unmap <Leader>fw
augroup END
```

But I think it would be a better solution to have a global setting to prevent default mappings from being mapped in the first place like many other plugins do.

Thanks!

**Comment by eugen0329** [comment]
Hi.

If there is at least one mapping for a esearch function then esearch won't add default mapping for this function (currently there are only two default mapping - for general purpose search and for searching a word under the cursor). So if you do `call   esearch#map('anyothermapping',    'esearch-word-under-cursor')` you won't get any bindings for `<leader>fw` . Or do you mean adding a config to prevent default mappings at all (like `let g:esearch = {'default_mappings': 0}`)?

**Comment by eugen0329** [comment]
Implemented default_mappings option. Please, update the plugin and let me know if it works for you.

**Comment by pwntester** [comment]
Thanks, I think that a better solution. Other plugins use same approach, for example:

````
let g:gitgutter_map_keys = 0
```

or 

```
let g:bclose_no_plugin_maps = 1
```

Thanks!

**Comment by pwntester** [comment]
The only thing is that with the following settings:

```
let g:esearch = {
  \ 'adapter':    'ag',
  \ 'backend':    'nvim',
  \ 'out':        'qflist',
  \ 'batch_size': 1000,
  \ 'use':        [],
  \}
let g:esearch = {'default_mappings': 0}
call esearch#map('r/', 'esearch')
```

The prompt is pre-populated with the last visual selection (even if no longer selected), even though I set `'use': []`

Im pretty sure this did not happen before updating the plugin, but I cant be 100% sure.

**Comment by eugen0329** [comment]
If the code above is from your vimrc then you've just reassigned all your `g:esearch` options with the dict with only default_mapping option set  :)

Please, try to use the following snippet:
```vim
let g:esearch = {
  \ 'adapter':    'ag',
  \ 'backend':    'nvim',
  \ 'out':        'qflist',
  \ 'batch_size': 1000,
  \ 'use':        [],
  \ 'default_mappings': 0,
  \}
call esearch#map('r/', 'esearch')
```

**Comment by pwntester** [comment]
Ouch, didnt realize it was the same dict :facepalm:

Thanks!
