### ISSUE TITLE
now required to set default_mappings

### ISSUE THREAD

**Issue by tmccombs** [eugen0329/vim-esearch#48]
I previously had this configuration:
```
let g:esearch = {
      \ 'adapter' : 'rg',
      \ 'out': 'qflist',
      \ 'use': ['visual', 'last', 'hlsearch']
      \}
```

After https://github.com/eugen0329/vim-esearch/commit/32cebe74a779e0405147955236736a7d417f89ea#diff-bae1852c6d6cbd437c0abf3d94447b4a

the default key bindings no longer worked, unless I added `'default_mappings': 1` to the dict. This was a little unexpected, and the README doesn't say that that option is required in order to get the default mappings.

**Comment by eugen0329** [comment]
Hi.

Nice catch, thanks! Please, update the plugin and let me know whether the bug is fixed or not.

**Comment by tmccombs** [comment]
That fixed it. Thanks!
