### ISSUE TITLE
Invalid relative path resolving with git adapter

### ISSUE THREAD

**Issue by eugen0329** [eugen0329/vim-esearch#50]
Originally reported in #27

Within nerdtree window put the cursor to `security/` and press esearch keys combination to start searching in the directory (must be different than your cwd):
```
/tmp/
   service/
>>>>>security/<<<<<
       myFile.ext
     other_file.txt
```
When trying to open a file in the results window by clicking enter or `o` file won't open and vim will try to create a new one. Can be reproduced with `let g:esearch = { 'adapter': 'git', 'out': 'win'}`.

**Comment by eugen0329** [comment]
@Spope,
please, try to update the plugin and check if everything works fine.

**Comment by Spope** [comment]
It works perfect now with git adapter. Thank you for your reactivity.

**Comment by eugen0329** [comment]
Cool! Thanks for your report too.
