### ISSUE TITLE
Search in new buffer instead of tab

### ISSUE THREAD

**Issue by pbogut** [eugen0329/vim-esearch#6]
Hi,

Esearch results appear in a new tab when selected option is `win` (that's missleading btw, as Vim has windows and tabs and you refer to the tab by `win`...).

Can we have the option to open it in new buffer without creating a new tab in the process?

Thanks.

**Comment by eugen0329** [comment]
Thanks for your report!

> (that's missleading btw, as Vim has windows and tabs and you refer to the tab by win...).

ESearch #win name refers to a target, where to put search results rather than location of a suitable window in **any** tab.

> Can we have the option to open it in new buffer...

It already exists. You can set any command to open new window with `g:esearch#out#win#open` (default is *tabnew*) or even leave it blank to open esearch buffer within the current window (added in  b8749d7, so you need to update plugin).
Actually, you can use another output target like 'qflist' or even implement your own.

But probably, it will be better to call it #buf instead of #win...

> ... open it in new buffer ..

Exactly this behavior you can achieve with:
```vim
let g:esearch#out#win#open = 'new'
```

I plan to finish the documentation in the next few weeks, so there will be a lot

**Comment by pbogut** [comment]
That makes more sense now, thanks for the clarification.

However, I still can't get the desired behaviour. The closest one to my needs is to use `enew` as it is creating a new buffer in the current window but with this option, ESearch leaves empty buffers after searching for the same thing again (As it probably goes to the first search but creating new buffer anyway).

Is that something that can be fixed?

Cheers

**Comment by pbogut** [comment]
@eugen0329 
I was checking the code, looking for the possible solutions for my problem. I can make it work for my needs but not sure if that's ok for you.

Right now when you search the same term multiple times with option `new` it will create another split and empty buffer as well (like with `enew`).

What works for me without changing the current tab behaviour is to wipeout buffer if it's not currently visible (or selected in tab) and create a new one. Works as expected for `tabnew`, `new` , `enew` and empty value as well. See PR #7.

Do you think that's a good way to go?

**Comment by eugen0329** [comment]
Sorry for the late reply. I had too much work.

Hmm, looks good, thanks:) I'll merge it.

**Comment by dkirchhof** [comment]
Sorry for commenting such an old issue, but i'm struggling with the same problem. As the esearch api changed and the `esearch#out#win#open` option is now deprecated, i want to override the `win_new` function.  
Unfortunately i don't get it...
I'm using nvim and the config is written in lua, but as i'm not able to call the `esearch#buf#goto_or_open` function from my lua script (it's undefined - don't know why), i'm using the `vim.cmd` function anyways.

```lua
-- no chance to get it working
-- local function openBuffer(esearch)
--     do something heare
-- end

vim.g.esearch = {
    name = '[esearch]',
    live_update = false,
    root_markers = { }, 
    -- win_new = openBuffer,
}

-- default -> works
-- vim.cmd([[let g:esearch.win_new = {esearch -> esearch#buf#goto_or_open(esearch.name, 'tabnew')}]])

-- i have no idea, what to write
-- vim.cmd([[let g:esearch.win_new = {esearch -> nvim_create_buf(1, 0)}]])
```

**Comment by eugen0329** [comment]
Neovim lua has an api to call viml functions. Try:
```vim
vim.g.esearch = {
    name = '[esearch]',
    live_update = false,
    root_markers = { }, 
    win_new = function(esearch) vim.fn['esearch#buf#goto_or_open'](esearch.name, 'tabnew') end,
}
```

**Comment by dkirchhof** [comment]
Wow, thanks for the quick response, but the real problem is that i wan't to open the search results in a new buffer not in a new tab.

**Comment by eugen0329** [comment]
So you would like to write results into a hidden buffer?

**Comment by dkirchhof** [comment]
The buffer should be listed, so i can switch from the results buffer to another file (e.g. by pressing enter) and back again.
For a new search, i don't know, if i want to replace the old (existing) search buffer or create a new one. It doesn't matter.

**Comment by eugen0329** [comment]
Does 
```vim
vim.g.esearch = {
    name = '[esearch]',
    win_new = function(esearch) vim.fn['esearch#buf#goto_or_open'](esearch.name, 'vsplit') end,
}
```
work for you?

**Comment by dkirchhof** [comment]
This works, but it will open the search in a vertical split. It should "replace" the current one. Just like if i'm using `:enew`.

**Comment by eugen0329** [comment]
You mean open on top of the current window? Like:
```vim
vim.g.esearch = {
    name = '[esearch]',
    win_new = function(esearch) vim.cmd('noswap edit ' .. esearch.name) end,
}
```

**Comment by dkirchhof** [comment]
Yes :) Exactly. Thanks
