### ISSUE TITLE
disable default mapping when redefining

### ISSUE THREAD

**Issue by subnixr** [eugen0329/vim-esearch#8]
I followed the readme to redefine a mapping

```
call esearch#map('<leader>s', 'esearch')
```

While it works, I still have `<leader>ff` mapped to esearch functionality.
`:map` confirms it (I've  set `<space>` as leader):

```
   <Space>s      <Plug>(esearch)
   <Space>ff     <Plug>(esearch)
```

I've also placed `unmap <Leader>ff` (tried both before and after `call esearch#map ...`), but neovim complains about it `E31: No such mapping`

**Comment by eugen0329** [comment]
Unfortunately, ESearch mappings back end needs to be completely rewritten. I plan to fix it during this week, but now you can temporarily insert these lines into your vimrc:
```viml
augroup TmpWorkaroundWithEsearch
  au!
  au VimEnter * unmap <Leader>ff
augroup END
```

**Comment by wwwdata** [comment]
what I did to restore my original `<leader> ff` mapping was defining an auto command. This will then be always executed last and overrides the plugins mapping again. So you can also do something like this:

```vim
autocmd VimEnter * nmap <leader>ff :Files<CR>
```

Really great plugin, thank you a lot for this!
