### ISSUE TITLE
Add ripgrep adapter support

### ISSUE THREAD

**Issue by munyari** [eugen0329/vim-esearch#9]
Ripgrep is a new search tool, similar to the Silver Searcher but faster
https://github.com/BurntSushi/ripgrep
http://blog.burntsushi.net/ripgrep/

**Comment by eugen0329** [comment]
Sounds great! I'll take a look.

**Comment by munyari** [comment]
I'll make a PR if you're open to it.

**Comment by eugen0329** [comment]
Close because the PR is already merged.
